language: cpp
sudo: required
dist: trusty
compiler:
    - clang
    - gcc
before_install:
    - sudo pip install --upgrade pip
    - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
    - echo "yes" | sudo add-apt-repository 'deb http://llvm.org/apt/trusty/ llvm-toolchain-trusty-3.9 main'
    - wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key | sudo apt-key add -
    - sudo apt-get -qq update
    - sudo apt-get install -y g++-6 libgcc-6-dev libopenmpi-dev openmpi-bin
before_script:
    - mkdir build
    - cd build
    - if [[ "$CXX" == "g++" ]]; then export CXX=g++-6; export CC=gcc-6; cmake ..; fi
    - if [[ "$CXX" == "clang++" ]]; then cmake ..; fi
script:
    - make -j2
after_success:
    - ctest
#- if [[ "$CXX" =~ ^g.* ]]; then make coverage && coveralls --lcov-file coverage.info --no-gcov ; fi
